import type { Product } from '../contexts/DataContext';

const now = new Date().toISOString();

function makeId(sku: string): string {
  return sku.toLowerCase().replace(/[^a-z0-9]/g, '-');
}

export const SEED_PRODUCTS: Product[] = [
  // ─── The Ordinary ───────────────────────────────────────────────────────────
  {
    id: makeId('TO-NIACINAMIDE-30'),
    sku: 'TO-NIACINAMIDE-30',
    name: 'The Ordinary Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    category: 'Serums',
    type: '30ml',
    price: 8.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw2a8a9c9a/Images/products/The%20Ordinary/rdn-niacinamide-10pct-zinc-1pct-30ml.png?sw=800&sh=800&sm=fit',
    rating: 4.7,
    reviews: 2840,
    country: 'UK',
    stock: 4,
    description: 'A high-strength vitamin and mineral formula designed to visibly reduce the appearance of blemishes, balance sebum activity, and improve skin clarity.',
    overview: 'A high-strength vitamin and mineral formula designed to visibly reduce the appearance of blemishes, balance sebum activity, and improve skin clarity. This lightweight serum is ideal for oily, congested, or breakout-prone skin.',
    benefits: [
      'Reduces the appearance of blemishes and breakouts',
      'Controls excess oil and shine',
      'Minimizes enlarged pores',
      'Brightens and evens out skin tone',
      'Strengthens the skin barrier',
    ],
    ingredients: [
      { name: 'Niacinamide', percentage: '10%', description: 'Brightens skin tone, reduces blemishes, and strengthens the skin barrier' },
      { name: 'Zinc PCA', percentage: '1%', description: 'Helps to balance oil production and reduce inflammation' },
    ],
    howToUse: [
      'Apply a few drops to the entire face in the morning and evening before heavier creams.',
      'Do not use with Vitamin C (ascorbic acid) in the same routine.',
      'Patch test before first use.',
    ],
    specificationTags: ['Oily Skin', 'Acne-Prone', 'Blemish Control', 'Pore Minimizing', 'Oil Control'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-NIACINAMIDE-POWDER'),
    sku: 'TO-NIACINAMIDE-POWDER',
    name: 'The Ordinary 100% Niacinamide Powder',
    brand: 'The Ordinary',
    category: 'Treatments',
    type: '20g',
    price: 6.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw4e5a6b7c/Images/products/The%20Ordinary/rdn-100pct-niacinamide-powder-20g.png?sw=800&sh=800&sm=fit',
    rating: 4.5,
    reviews: 620,
    country: 'UK',
    stock: 2,
    description: 'A versatile, high-purity powder that allows you to create a personalized skincare solution tailored to your needs.',
    overview: 'The Ordinary 100% Niacinamide Powder is a versatile, high-purity powder that allows you to create a personalized skincare solution. Niacinamide (Vitamin B3) visibly reduces the appearance of blemishes, enlarged pores, and uneven skin tone while regulating excess oil production.',
    benefits: [
      'Reduces the appearance of enlarged pores and uneven skin tone',
      'Controls excess oil and shine',
      'Improves skin clarity and smoothness',
      'Brightens overall complexion',
      'Allows for personalized skincare combinations',
    ],
    ingredients: [
      { name: 'Niacinamide', percentage: '100%', description: 'A multi-functional ingredient that visibly improves skin texture and tone while helping to regulate sebum production' },
    ],
    howToUse: [
      'Mix a small amount (a quarter scoop) with a water-based treatment in the palm of your hand.',
      'Apply to the face, avoiding the eye area.',
      'Recommended mixing mediums include The Ordinary Hyaluronic Acid 2% + B5.',
      'Do not mix with direct acids, pure Vitamin C, or peptides.',
    ],
    specificationTags: ['Oily Skin', 'Blemish Control', 'Customizable', 'Brightening'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-CAFFEINE-30'),
    sku: 'TO-CAFFEINE-30',
    name: 'The Ordinary Caffeine Solution 5% + EGCG',
    brand: 'The Ordinary',
    category: 'Eye Care',
    type: '30ml',
    price: 7.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw5f6a7b8c/Images/products/The%20Ordinary/rdn-caffeine-solution-5pct-egcg-30ml.png?sw=800&sh=800&sm=fit',
    rating: 4.6,
    reviews: 1950,
    country: 'UK',
    stock: 2,
    description: 'A lightweight eye serum formulated to reduce the appearance of puffiness and dark circles.',
    overview: 'A lightweight eye serum formulated to reduce the appearance of puffiness and dark circles. Powered by a high concentration of caffeine and EGCG (a potent antioxidant from green tea), this serum energizes the under-eye area and refreshes tired-looking eyes.',
    benefits: [
      'Visibly reduces puffiness and under-eye bags',
      'Diminishes the appearance of dark circles',
      'Soothes and protects with antioxidants',
      'Lightweight, fast-absorbing texture',
      'Refreshes and revitalizes tired eyes',
    ],
    ingredients: [
      { name: 'Caffeine', percentage: '5%', description: 'Helps constrict blood vessels to reduce puffiness' },
      { name: 'EGCG', description: 'A green tea-derived antioxidant that soothes and protects the delicate eye area' },
    ],
    howToUse: [
      'Apply a small amount to the under-eye area in the morning and evening.',
      'Use fingertips to pat in gently until absorbed.',
      'Avoid direct contact with eyes.',
    ],
    specificationTags: ['All Skin Types', 'Dark Circles', 'Puffiness', 'Eye Care'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-HA-B5-CERAMIDES-30'),
    sku: 'TO-HA-B5-CERAMIDES-30',
    name: 'The Ordinary Hyaluronic Acid 2% + B5 (with Ceramides)',
    brand: 'The Ordinary',
    category: 'Serums',
    type: '30ml',
    price: 10.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw67286abd/Images/products/The%20Ordinary/ord-hyaluronic-acid-2pct-B5-30ml-Clr-Acu.png?sw=800&sh=800&sm=fit',
    rating: 4.8,
    reviews: 3100,
    country: 'UK',
    stock: 2,
    description: 'A deeply hydrating serum that combines multi-depth hyaluronic acid, pro-vitamin B5, and skin-repairing ceramides.',
    overview: 'A deeply hydrating serum that combines multi-depth hyaluronic acid, pro-vitamin B5, and skin-repairing ceramides to replenish moisture, strengthen the skin barrier, and leave skin feeling plump and smooth.',
    benefits: [
      'Intensely hydrates and plumps the skin',
      'Strengthens and restores the skin barrier',
      'Improves skin texture and elasticity',
      'Soothes dryness and irritation',
      'Lightweight, non-greasy formula',
    ],
    ingredients: [
      { name: 'Hyaluronic Acid', percentage: '2%', description: 'At multiple molecular weights for deep and surface hydration' },
      { name: 'Vitamin B5 (Panthenol)', description: 'Enhances surface hydration and soothes the skin' },
      { name: 'Ceramides', description: 'Help reinforce the skin barrier and retain moisture' },
    ],
    howToUse: [
      'Apply a few drops to the face in the morning and evening before creams.',
      'Use on damp skin for best results.',
      'Follow with a moisturizer to seal in hydration.',
    ],
    specificationTags: ['All Skin Types', 'Dry Skin', 'Hydration', 'Barrier Repair'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-HA-B5-30'),
    sku: 'TO-HA-B5-30',
    name: 'The Ordinary Hyaluronic Acid 2% + B5',
    brand: 'The Ordinary',
    category: 'Serums',
    type: '30ml / 60ml',
    price: 9.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw8a9b0c1d/Images/products/The%20Ordinary/rdn-hyaluronic-acid-2pct-b5-30ml.png?sw=800&sh=800&sm=fit',
    rating: 4.7,
    reviews: 2600,
    country: 'UK',
    stock: 3,
    description: 'Multi-depth hydration serum that combines low, medium, and high molecular weight Hyaluronic Acid with Vitamin B5.',
    overview: 'A deeply hydrating serum that combines low, medium, and high molecular weight Hyaluronic Acid with Vitamin B5 to provide multi-layered moisture and improve skin elasticity. This original formulation is a fan-favorite for instantly plumping and smoothing dehydrated skin.',
    benefits: [
      'Instantly hydrates and plumps the skin',
      'Improves skin smoothness and suppleness',
      'Supports skin repair and barrier function',
      'Lightweight, non-greasy, and layers well under makeup',
      'Suitable for all skin types',
    ],
    ingredients: [
      { name: 'Hyaluronic Acid Complex', percentage: '2%', description: 'Low, Medium & High molecular weight — attracts up to 1,000x its weight in water' },
      { name: 'Vitamin B5 (Panthenol)', description: 'Enhances surface hydration and supports healing' },
      { name: 'Glycerin', description: 'A natural humectant that helps retain moisture' },
    ],
    howToUse: [
      'Apply a few drops to the face in the morning and evening before creams.',
      'Use on damp skin for best results.',
      'Follow with a moisturizer to lock in hydration.',
    ],
    specificationTags: ['All Skin Types', 'Dehydrated Skin', 'Hydration', 'Plumping'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-SALICYLIC-BODY-240'),
    sku: 'TO-SALICYLIC-BODY-240',
    name: 'The Ordinary Salicylic Acid 0.5% Body Serum',
    brand: 'The Ordinary',
    category: 'Body Care',
    type: '240ml',
    price: 12.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw9b0c1d2e/Images/products/The%20Ordinary/rdn-salicylic-acid-0pct5-body-serum-240ml.png?sw=800&sh=800&sm=fit',
    rating: 4.5,
    reviews: 870,
    country: 'UK',
    stock: 2,
    description: 'A lightweight, non-sticky body serum designed to exfoliate, unclog pores, and visibly improve skin texture.',
    overview: 'A lightweight, non-sticky body serum designed to exfoliate, unclog pores, and visibly improve skin texture. Perfect for addressing back and chest acne, rough patches, and dull skin.',
    benefits: [
      'Clears body acne and prevents new breakouts',
      'Smooths rough, bumpy skin (including keratosis pilaris)',
      'Unclogs pores and reduces congestion',
      'Hydrates and supports the skin barrier',
      'Non-comedogenic and fast-absorbing',
    ],
    ingredients: [
      { name: 'Salicylic Acid', percentage: '0.5%', description: 'BHA that exfoliates deep inside pores, reducing breakouts and improving texture' },
      { name: 'Glycerin', description: 'Hydrates and softens the skin' },
      { name: 'Saccharide Isomerate', description: 'Binds moisture and strengthens the skin barrier' },
    ],
    howToUse: [
      'Apply a thin layer once daily to clean, dry skin on affected body areas.',
      'Avoid face and eye area.',
      'Use sunscreen during the day when applying to sun-exposed areas.',
    ],
    specificationTags: ['Acne-Prone', 'Body Care', 'Keratosis Pilaris', 'Exfoliating'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-GLYCOLIC-TONER-240'),
    sku: 'TO-GLYCOLIC-TONER-240',
    name: 'The Ordinary Glycolic Acid 7% Exfoliating Toner',
    brand: 'The Ordinary',
    category: 'Toners',
    type: '240ml',
    price: 11.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw0c1d2e3f/Images/products/The%20Ordinary/rdn-glycolic-acid-7pct-toning-solution-240ml.png?sw=800&sh=800&sm=fit',
    rating: 4.6,
    reviews: 3200,
    country: 'UK',
    stock: 3,
    description: 'A gentle yet powerful exfoliating toner formulated with 7% glycolic acid to enhance skin clarity, smoothness, and radiance.',
    overview: 'A gentle yet powerful exfoliating toner formulated with 7% glycolic acid to enhance skin clarity, smoothness, and radiance. Ideal for dull, uneven, or textured skin.',
    benefits: [
      'Gently exfoliates to improve skin texture',
      'Boosts radiance and glow',
      'Minimizes appearance of pores',
      'Smooths rough or uneven skin tone',
      'Calms and hydrates with botanical extracts',
    ],
    ingredients: [
      { name: 'Glycolic Acid', percentage: '7%', description: 'AHA that exfoliates the skin\'s surface to promote cell turnover and improve clarity' },
      { name: 'Aloe Vera', description: 'Soothes and hydrates the skin' },
      { name: 'Tasmanian Pepperberry Extract', description: 'Reduces potential irritation from glycolic acid' },
      { name: 'Ginseng Root Extract', description: 'Promotes a healthy, radiant look' },
    ],
    howToUse: [
      'Use once daily, preferably in the evening.',
      'After cleansing, saturate a cotton pad and sweep across the face and neck.',
      'Avoid the eye area. Do not rinse.',
      'Always use sunscreen during the day while using this product.',
    ],
    specificationTags: ['Normal Skin', 'Oily Skin', 'Combination Skin', 'Exfoliating', 'Brightening'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-AZELAIC-30'),
    sku: 'TO-AZELAIC-30',
    name: 'The Ordinary Azelaic Acid Suspension 10%',
    brand: 'The Ordinary',
    category: 'Treatments',
    type: '30ml',
    price: 9.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw1d2e3f4a/Images/products/The%20Ordinary/rdn-azelaic-acid-suspension-10pct-30ml.png?sw=800&sh=800&sm=fit',
    rating: 4.5,
    reviews: 1100,
    country: 'UK',
    stock: 2,
    description: 'A multi-functional brightening formula that visibly improves skin tone, refines texture, and reduces the look of blemishes.',
    overview: 'A multi-functional brightening formula that visibly improves skin tone, refines texture, and reduces the look of blemishes. Powered by Azelaic Acid, a naturally occurring acid found in grains, known for its skin-soothing, antioxidant, and clarifying properties.',
    benefits: [
      'Brightens uneven skin tone',
      'Reduces the appearance of blemishes and post-acne marks',
      'Refines skin texture and minimizes redness',
      'Lightweight, silicone-based formula for a smooth finish',
      'Suitable for daily use',
    ],
    ingredients: [
      { name: 'Azelaic Acid', percentage: '10%', description: 'Gently exfoliates, reduces inflammation, and targets discoloration' },
      { name: 'Dimethicone', description: 'Gives a smooth, matte finish and enhances spreadability' },
    ],
    howToUse: [
      'Apply a small amount to the face in the morning or evening.',
      'Use after water-based serums and before heavier creams.',
      'Always follow with sunscreen during the day.',
    ],
    specificationTags: ['Oily Skin', 'Acne-Prone', 'Sensitive Skin', 'Brightening', 'Redness'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-NMF-HA-30'),
    sku: 'TO-NMF-HA-30',
    name: 'The Ordinary Natural Moisturizing Factors + HA',
    brand: 'The Ordinary',
    category: 'Moisturizers',
    type: '30ml / 100ml',
    price: 8.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw2e3f4a5b/Images/products/The%20Ordinary/rdn-natural-moisturizing-factors-ha-30ml.png?sw=800&sh=800&sm=fit',
    rating: 4.7,
    reviews: 2400,
    country: 'UK',
    stock: 1,
    description: 'A non-greasy, deeply hydrating moisturizer that delivers immediate and lasting hydration with ingredients naturally found in the skin.',
    overview: 'A non-greasy, deeply hydrating moisturizer that delivers immediate and lasting hydration with ingredients naturally found in the skin. Formulated with multiple amino acids, fatty acids, and hyaluronic acid to support a healthy, supple skin barrier.',
    benefits: [
      'Provides long-lasting hydration',
      'Strengthens the skin\'s natural moisture barrier',
      'Smooths and softens dry, rough skin',
      'Lightweight and non-comedogenic',
      'Suitable for daily use, morning and night',
    ],
    ingredients: [
      { name: 'Natural Moisturizing Factors (NMF)', description: 'Amino acids, fatty acids, urea, PCA, and more to mimic skin\'s natural hydration system' },
      { name: 'Hyaluronic Acid', description: 'Attracts and retains moisture in the skin' },
    ],
    howToUse: [
      'Apply after serums as the last step in your skincare routine.',
      'Use morning and night for optimal hydration and skin comfort.',
    ],
    specificationTags: ['All Skin Types', 'Dry Skin', 'Sensitive Skin', 'Hydration', 'Barrier Repair'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-NMF-PHYTOCERAMIDES-100'),
    sku: 'TO-NMF-PHYTOCERAMIDES-100',
    name: 'The Ordinary Natural Moisturizing Factors + PhytoCeramides',
    brand: 'The Ordinary',
    category: 'Moisturizers',
    type: '100ml',
    price: 10.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw0a1b2c3d/Images/products/The%20Ordinary/rdn-natural-moisturizing-factors-phytoceramides-30ml.png?sw=800&sh=800&sm=fit',
    rating: 4.6,
    reviews: 980,
    country: 'UK',
    stock: 2,
    description: 'A deeply nourishing moisturizer designed to support the skin barrier and deliver long-lasting hydration with PhytoCeramides.',
    overview: 'A deeply nourishing moisturizer designed to support the skin barrier and deliver long-lasting hydration. This upgraded version of the original NMF formula includes skin-mimicking PhytoCeramides, plant-derived lipids that help restore and strengthen the skin\'s protective layer.',
    benefits: [
      'Provides immediate and long-term hydration',
      'Strengthens the skin barrier with PhytoCeramides',
      'Smooths rough texture and softens dry patches',
      'Helps prevent moisture loss',
      'Suitable for sensitive, dry, and compromised skin',
    ],
    ingredients: [
      { name: 'Natural Moisturizing Factors (NMF)', description: 'Amino acids, fatty acids, urea, PCA, and more' },
      { name: 'PhytoCeramides', description: 'Plant-derived ceramides that reinforce the skin barrier and improve moisture retention' },
      { name: 'Hyaluronic Acid', description: 'Attracts and retains water in the skin for deep hydration' },
    ],
    howToUse: [
      'Apply to face and neck after serums, morning and night.',
      'Use as the final step in your skincare routine to lock in hydration.',
    ],
    specificationTags: ['All Skin Types', 'Dry Skin', 'Sensitive Skin', 'Barrier Repair', 'Anti-Aging'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-NMF-BETAGLUCAN-100'),
    sku: 'TO-NMF-BETAGLUCAN-100',
    name: 'The Ordinary Natural Moisturizing Factors + Beta Glucan',
    brand: 'The Ordinary',
    category: 'Moisturizers',
    type: '100ml',
    price: 10.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw1b2c3d4e/Images/products/The%20Ordinary/rdn-natural-moisturizing-factors-beta-glucan-30ml.png?sw=800&sh=800&sm=fit',
    rating: 4.6,
    reviews: 760,
    country: 'UK',
    stock: 1,
    description: 'A next-generation moisturizer that delivers powerful hydration and skin barrier support with a soothing, lightweight finish.',
    overview: 'A next-generation moisturizer that delivers powerful hydration and skin barrier support with a soothing, lightweight finish. Combines Natural Moisturizing Factors with Beta Glucan, a potent skin-repairing ingredient known for calming sensitivity, reducing redness, and boosting resilience.',
    benefits: [
      'Provides deep and lasting hydration',
      'Calms and soothes sensitive or irritated skin',
      'Strengthens the skin barrier',
      'Improves skin texture and softness',
      'Supports recovery from dryness or irritation',
    ],
    ingredients: [
      { name: 'Natural Moisturizing Factors (NMF)', description: 'Amino acids, fatty acids, and urea that mimic skin\'s own hydration system' },
      { name: 'Beta Glucan', description: 'A powerful humectant and antioxidant that soothes and strengthens sensitive skin' },
      { name: 'Hyaluronic Acid', description: 'Binds water to skin and boosts hydration' },
    ],
    howToUse: [
      'Apply to the face and neck after serums, morning and evening.',
      'Ideal as the final step in your skincare routine to seal in moisture and comfort.',
    ],
    specificationTags: ['All Skin Types', 'Sensitive Skin', 'Dry Skin', 'Hydration', 'Soothing'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-SQUALANE-CLEANSER-50'),
    sku: 'TO-SQUALANE-CLEANSER-50',
    name: 'The Ordinary Squalane Cleanser',
    brand: 'The Ordinary',
    category: 'Cleansers',
    type: '50ml / 150ml',
    price: 9.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw2c3d4e5f/Images/products/The%20Ordinary/rdn-squalane-cleanser-50ml.png?sw=800&sh=800&sm=fit',
    rating: 4.7,
    reviews: 2100,
    country: 'UK',
    stock: 2,
    description: 'A gentle, skin-friendly cleanser that effectively removes makeup, dirt, and impurities without stripping the skin.',
    overview: 'A gentle, skin-friendly cleanser that effectively removes makeup, dirt, and impurities without stripping the skin. Formulated with squalane and skin-identical esters, this balm-to-oil cleanser leaves skin feeling clean, soft, and hydrated.',
    benefits: [
      'Gently removes makeup and impurities',
      'Leaves skin soft and moisturized',
      'Non-comedogenic and soap-free',
      'Suitable for daily use, morning and night',
      'Ideal first step in a double cleanse routine',
    ],
    ingredients: [
      { name: 'Squalane', description: 'Hydrates and helps support the skin barrier' },
      { name: 'Lipophilic Esters', description: 'Effectively dissolve makeup and impurities' },
      { name: 'Glycerin', description: 'Attracts moisture and keeps skin smooth' },
    ],
    howToUse: [
      'Dispense a small amount into hands and rub together to warm.',
      'Massage onto dry face to dissolve makeup and dirt.',
      'Rinse with warm water.',
      'Use alone or as the first step in a double cleanse.',
    ],
    specificationTags: ['All Skin Types', 'Sensitive Skin', 'Acne-Prone', 'Makeup Removal', 'Gentle Cleansing'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-SQUALANE-LIP-BALM-15'),
    sku: 'TO-SQUALANE-LIP-BALM-15',
    name: 'The Ordinary Squalane + Amino Acids Lip Balm',
    brand: 'The Ordinary',
    category: 'Lip Care',
    type: '15ml',
    price: 6.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw3d4e5f6a/Images/products/The%20Ordinary/rdn-squalane-amino-acids-lip-balm.png?sw=800&sh=800&sm=fit',
    rating: 4.5,
    reviews: 540,
    country: 'UK',
    stock: 1,
    description: 'A deeply hydrating and restorative lip treatment formulated with skin-identical ingredients to nourish, smooth, and protect dry or chapped lips.',
    overview: 'A deeply hydrating and restorative lip treatment formulated with skin-identical ingredients to nourish, smooth, and protect dry or chapped lips. Combines squalane, amino acids, and emollients to replenish moisture and support a healthy lip barrier.',
    benefits: [
      'Hydrates and softens dry, cracked lips',
      'Strengthens the delicate lip barrier',
      'Provides long-lasting comfort without stickiness',
      'Lightweight, silky texture ideal for daily use',
      'Fragrance-free and suitable for sensitive skin',
    ],
    ingredients: [
      { name: 'Squalane', description: 'A non-comedogenic hydrator that mimics natural skin oils' },
      { name: 'Amino Acids', description: 'Help repair and maintain healthy skin structure' },
      { name: 'Lipid-Rich Emollients', description: 'Smooth and protect the lips from moisture loss' },
    ],
    howToUse: [
      'Apply to lips as needed throughout the day.',
      'Can be used alone or under lipstick for extra hydration.',
    ],
    specificationTags: ['All Skin Types', 'Sensitive Skin', 'Lip Care', 'Hydration'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-AHA-BHA-PEEL-30'),
    sku: 'TO-AHA-BHA-PEEL-30',
    name: 'The Ordinary AHA 30% + BHA 2% Peeling Solution',
    brand: 'The Ordinary',
    category: 'Treatments',
    type: '30ml',
    price: 10.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw3f4a5b6c/Images/products/The%20Ordinary/rdn-aha-30pct-bha-2pct-peeling-solution-30ml.png?sw=800&sh=800&sm=fit',
    rating: 4.6,
    reviews: 4200,
    country: 'UK',
    stock: 1,
    description: 'A powerful 10-minute exfoliating facial designed to deeply cleanse pores and visibly improve skin texture and clarity.',
    overview: 'A powerful 10-minute exfoliating facial designed to deeply cleanse pores and visibly improve skin texture and clarity. Combines AHA and BHA to remove dead skin cells, unclog pores, and reveal brighter, more radiant skin.',
    benefits: [
      'Exfoliates dead skin for smoother texture',
      'Deeply cleanses and unclogs pores',
      'Helps reduce blemishes and congestion',
      'Boosts radiance and skin clarity',
      'Improves uneven tone over time',
    ],
    ingredients: [
      { name: 'AHA (Glycolic, Lactic, Tartaric & Citric Acids)', percentage: '30%', description: 'Remove dead skin cells and promote cell turnover' },
      { name: 'Salicylic Acid (BHA)', percentage: '2%', description: 'Penetrates pores to reduce congestion and breakouts' },
      { name: 'Tasmanian Pepperberry Derivative', description: 'Reduces irritation from acid use' },
      { name: 'Hyaluronic Acid Crosspolymer', description: 'Hydrates and protects skin' },
    ],
    howToUse: [
      'Use in the evening, no more than twice a week.',
      'Apply a small amount evenly to clean, dry skin.',
      'Leave on for no more than 10 minutes, then rinse thoroughly with lukewarm water.',
      'Do not use on wet skin. Avoid the eye area.',
      'Follow with a gentle moisturizer. Always use sunscreen during the day.',
    ],
    tips: ['Warning: This is a highly potent formula. A patch test is strongly recommended before first use.'],
    specificationTags: ['Oily Skin', 'Combination Skin', 'Acne-Prone', 'Exfoliating', 'Brightening'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-RETINOL-05-30'),
    sku: 'TO-RETINOL-05-30',
    name: 'The Ordinary Retinol 0.5% in Squalane',
    brand: 'The Ordinary',
    category: 'Treatments',
    type: '30ml',
    price: 8.60,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw4a5b6c7d/Images/products/The%20Ordinary/rdn-retinol-0pct5-in-squalane-30ml.png?sw=800&sh=800&sm=fit',
    rating: 4.5,
    reviews: 1530,
    country: 'UK',
    stock: 1,
    description: 'A highly effective, medium-strength retinol serum that promotes smoother, more youthful-looking skin.',
    overview: 'A highly effective, medium-strength retinol serum that promotes smoother, more youthful-looking skin. Formulated in a base of squalane, this water-free solution reduces the appearance of fine lines, sun damage, and texture irregularities without over-drying the skin.',
    benefits: [
      'Improves appearance of fine lines and wrinkles',
      'Smooths skin texture and evens out tone',
      'Fights visible signs of photoaging',
      'Lightweight and moisturizing with squalane base',
      'Non-comedogenic and fragrance-free',
    ],
    ingredients: [
      { name: 'Retinol', percentage: '0.5%', description: 'A well-researched form of Vitamin A that accelerates cell turnover and collagen production' },
      { name: 'Squalane', description: 'A non-greasy hydrator that mimics natural skin oils and reduces irritation' },
    ],
    howToUse: [
      'Apply a small amount in the evening, after water-based serums and before heavier creams.',
      'Use only at night and follow with sunscreen during the day.',
      'Start with 2–3 times per week, gradually increasing frequency.',
    ],
    tips: ['Retinol can increase skin sensitivity, especially to sunlight. A patch test is recommended before full use.'],
    specificationTags: ['Normal Skin', 'Oily Skin', 'Combination Skin', 'Anti-Aging', 'Fine Lines'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-MULTI-PEPTIDE-EYE-15'),
    sku: 'TO-MULTI-PEPTIDE-EYE-15',
    name: 'The Ordinary Multi-Peptide Eye Serum',
    brand: 'The Ordinary',
    category: 'Eye Care',
    type: '15ml',
    price: 14.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw5b6c7d8e/Images/products/The%20Ordinary/rdn-multi-peptide-eye-serum-15ml.png?sw=800&sh=800&sm=fit',
    rating: 4.6,
    reviews: 890,
    country: 'UK',
    stock: 2,
    description: 'A powerful yet lightweight eye serum that targets multiple signs of aging around the delicate eye area.',
    overview: 'A powerful yet lightweight eye serum that targets multiple signs of aging around the delicate eye area. Formulated with an advanced blend of peptides and supportive ingredients, this serum works to reduce the look of crow\'s feet, under-eye puffiness, and dark circles.',
    benefits: [
      'Reduces appearance of fine lines and crow\'s feet',
      'Visibly improves puffiness and dark circles',
      'Firms and smooths the under-eye area',
      'Hydrating, fast-absorbing formula',
      'Fragrance-free and non-irritating',
    ],
    ingredients: [
      { name: 'Multi-Peptide Complex', description: 'Palmitoyl Tetrapeptide-7, Palmitoyl Tripeptide-1, Acetyl Tetrapeptide-5, Argireline™ — targets dynamic wrinkles and eye puffiness' },
      { name: 'Niacinamide', description: 'Brightens and strengthens the skin barrier' },
      { name: 'Caffeine', description: 'Reduces puffiness and improves circulation' },
    ],
    howToUse: [
      'Apply a small amount to the eye contour area in the morning and evening.',
      'Use after cleansing and before creams or moisturizers.',
      'Gently tap with fingertips until absorbed.',
    ],
    specificationTags: ['All Skin Types', 'Sensitive Skin', 'Anti-Aging', 'Eye Care', 'Dark Circles'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-MULTI-PEPTIDE-HAIR-60'),
    sku: 'TO-MULTI-PEPTIDE-HAIR-60',
    name: 'The Ordinary Multi-Peptide Serum for Hair Density',
    brand: 'The Ordinary',
    category: 'Hair Care',
    type: '60ml',
    price: 18.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw6c7d8e9f/Images/products/The%20Ordinary/rdn-multi-peptide-serum-for-hair-density-60ml.png?sw=800&sh=800&sm=fit',
    rating: 4.4,
    reviews: 1200,
    country: 'UK',
    stock: 2,
    description: 'A concentrated leave-in serum specially formulated to support hair and scalp health, promoting the look of fuller, denser hair.',
    overview: 'A concentrated leave-in serum specially formulated to support hair and scalp health. Powered by an advanced blend of peptides, plant-based complexes, and caffeine, it helps promote the look of fuller, denser hair over time.',
    benefits: [
      'Improves appearance of hair thickness and density',
      'Supports scalp health and vitality',
      'Strengthens hair from the root',
      'Non-greasy, fast-absorbing, leave-in formula',
      'Suitable for all hair types and textures',
    ],
    ingredients: [
      { name: 'REDENSYL™, BAICAPIL™, Procapil™', description: 'Patented peptide complexes that support healthy hair growth and reduce fall' },
      { name: 'Caffeine', description: 'Energizes the scalp and improves follicle function' },
      { name: 'Biotinoyl Tripeptide-1 & Acetyl Tetrapeptide-3', description: 'Help improve scalp condition and hair strength' },
      { name: 'Castor Oil', description: 'Conditions and nourishes the scalp' },
    ],
    howToUse: [
      'Apply a few drops directly to a clean, dry scalp once daily, preferably at night.',
      'Massage gently and leave in. Do not rinse.',
      'Use consistently for visible results over time.',
    ],
    specificationTags: ['All Hair Types', 'Hair Density', 'Scalp Health', 'Hair Growth'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-UV-SPF45-30'),
    sku: 'TO-UV-SPF45-30',
    name: 'The Ordinary UV Filters SPF 45 Serum',
    brand: 'The Ordinary',
    category: 'Sunscreen',
    type: '30ml',
    price: 12.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw7d8e9f0a/Images/products/The%20Ordinary/rdn-uv-filters-spf-45-serum-30ml.png?sw=800&sh=800&sm=fit',
    rating: 4.5,
    reviews: 1450,
    country: 'UK',
    stock: 3,
    description: 'High-protection daily sunscreen in a lightweight serum texture with broad-spectrum SPF 45.',
    overview: 'The Ordinary UV Filters SPF 45 Serum offers broad-spectrum sun protection in a lightweight, non-greasy serum formula. Designed to shield the skin from harmful UVA and UVB rays, this innovative sunscreen combines advanced UV filters with skin-supporting ingredients.',
    benefits: [
      'Provides high-level SPF 45 protection against UVA/UVB rays',
      'Helps prevent sunburn and long-term sun damage',
      'Lightweight serum texture absorbs quickly',
      'Leaves no white cast or greasy residue',
      'Supports healthy, protected skin with added hydrators and antioxidants',
    ],
    ingredients: [
      { name: 'Broad-Spectrum UV Filters (SPF 45)', description: 'Avobenzone, Octocrylene, and Octinoxate for broad-spectrum protection' },
      { name: 'Antioxidants', description: 'Help to neutralize environmental damage and oxidative stress' },
      { name: 'Hydrating Agents', description: 'Maintain skin moisture barrier and comfort throughout the day' },
    ],
    howToUse: [
      'Apply liberally to the face and neck as the last step of your skincare routine in the morning.',
      'Reapply every two hours when exposed to sunlight, and after swimming or sweating.',
    ],
    specificationTags: ['All Skin Types', 'Sensitive Skin', 'Combination Skin', 'Sun Protection', 'SPF 45'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-SOOTHING-BARRIER-30'),
    sku: 'TO-SOOTHING-BARRIER-30',
    name: 'The Ordinary Soothing & Barrier Support Serum',
    brand: 'The Ordinary',
    category: 'Serums',
    type: '30ml',
    price: 11.90,
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw8e9f0a1b/Images/products/The%20Ordinary/rdn-soothing-and-barrier-support-serum-30ml.png?sw=800&sh=800&sm=fit',
    rating: 4.6,
    reviews: 780,
    country: 'UK',
    stock: 2,
    description: 'A universal serum designed to calm irritation, reduce redness, and reinforce the skin\'s natural barrier.',
    overview: 'A universal serum designed to calm irritation, reduce redness, and reinforce the skin\'s natural barrier. Formulated with a unique blend of vitamins, lipids, and humectants, this milky-textured serum is perfect for stressed, compromised, or sensitive skin.',
    benefits: [
      'Soothes signs of irritation and redness',
      'Strengthens and restores the skin\'s natural barrier',
      'Hydrates and softens rough or dry patches',
      'Helps skin recover from overuse of actives or environmental stress',
      'Non-comedogenic, fragrance-free, and suitable for sensitive skin',
    ],
    ingredients: [
      { name: 'Niacinamide (Vitamin B3)', description: 'Supports barrier repair and reduces redness' },
      { name: 'Vitamin B12 & Allantoin', description: 'Calming agents that relieve irritation' },
      { name: 'Ceramide Complex', description: 'Helps rebuild and maintain the skin barrier' },
      { name: 'Beta-Glucan & Bisabolol', description: 'Provide anti-inflammatory and soothing effects' },
      { name: 'Squalane & Glycerin', description: 'Deeply hydrate and prevent moisture loss' },
    ],
    howToUse: [
      'Apply a few drops to clean, dry skin in the morning and/or evening.',
      'Use after cleansing and before oils or creams.',
    ],
    specificationTags: ['All Skin Types', 'Sensitive Skin', 'Barrier Repair', 'Soothing', 'Redness'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('TO-ACNE-SET'),
    sku: 'TO-ACNE-SET',
    name: 'The Ordinary Acne Set – Clearer Skin Essentials',
    brand: 'The Ordinary',
    category: 'Sets & Kits',
    type: 'Set',
    price: 29.90,
    originalPrice: 38.60,
    badge: 'Bundle',
    image: 'https://theordinary.com/dw/image/v2/BFKJ_PRD/on/demandware.static/-/Sites-deciem-master/default/dw9f0a1b2c/Images/products/The%20Ordinary/rdn-acne-set.png?sw=800&sh=800&sm=fit',
    rating: 4.7,
    reviews: 640,
    country: 'UK',
    stock: 2,
    description: 'A targeted skincare routine designed to help reduce breakouts, control oil, and soothe inflamed skin.',
    overview: 'A targeted skincare routine designed to help reduce breakouts, control oil, and soothe inflamed skin. This curated set combines The Ordinary\'s best-selling formulas to visibly improve clarity, texture, and tone without stripping or irritating the skin.',
    benefits: [
      'Reduces acne and prevents future breakouts',
      'Minimizes appearance of pores and excess oil',
      'Soothes redness and inflammation',
      'Gently exfoliates and clears clogged pores',
      'Strengthens and hydrates the skin barrier',
    ],
    howToUse: [
      'AM: Cleanse with Squalane Cleanser → Apply Niacinamide 10% + Zinc 1% → Moisturize with NMF + HA',
      'PM: Cleanse → Apply Salicylic Acid Solution to affected areas → Niacinamide (if tolerated) → Moisturize',
    ],
    specificationTags: ['Oily Skin', 'Acne-Prone', 'Blemish Control', 'Starter Kit'],
    createdAt: now,
    updatedAt: now,
  },

  // ─── CeraVe ─────────────────────────────────────────────────────────────────
  {
    id: makeId('CV-MOISTURIZING-CREAM-454'),
    sku: 'CV-MOISTURIZING-CREAM-454',
    name: 'CeraVe Moisturizing Cream',
    brand: 'CeraVe',
    category: 'Moisturizers',
    type: '454g',
    price: 18.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products/moisturizing-cream/moisturizing-cream_front.jpg?rev=a5e3e3e3&w=900',
    rating: 4.8,
    reviews: 5600,
    country: 'USA',
    stock: 3,
    description: 'A rich, non-greasy formula developed with dermatologists to deliver deep and long-lasting hydration.',
    overview: 'CeraVe Moisturizing Cream is a rich, non-greasy formula developed with dermatologists to deliver deep and long-lasting hydration. Powered by essential ceramides and hyaluronic acid, this barrier-repairing cream helps restore the skin\'s protective layer. Ideal for both face and body.',
    benefits: [
      'Provides 24-hour hydration',
      'Restores and strengthens the skin\'s natural barrier',
      'Soothes and relieves dry, flaky, and rough skin',
      'Non-comedogenic and fragrance-free',
      'Suitable for both face and body use',
    ],
    ingredients: [
      { name: 'Ceramides (1, 3, 6-II)', description: 'Essential for reinforcing the skin barrier and retaining moisture' },
      { name: 'Hyaluronic Acid', description: 'Helps attract and retain hydration in the skin' },
      { name: 'Glycerin', description: 'A powerful humectant that draws moisture to the skin' },
      { name: 'Petrolatum', description: 'Provides a protective layer to lock in moisture' },
    ],
    howToUse: [
      'Apply liberally as often as needed, or as directed by a physician.',
      'Use on the face and body for all-day hydration.',
      'For best results, apply to damp skin after bathing or cleansing.',
    ],
    specificationTags: ['Dry Skin', 'Sensitive Skin', 'Eczema', 'All Ages', 'Fragrance-Free'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-MOISTURIZING-LOTION-236'),
    sku: 'CV-MOISTURIZING-LOTION-236',
    name: 'CeraVe Moisturizing Lotion',
    brand: 'CeraVe',
    category: 'Moisturizers',
    type: '236ml / 473ml',
    price: 14.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products/moisturizing-lotion/moisturizing-lotion_front.jpg?rev=b5e3e3e3&w=900',
    rating: 4.7,
    reviews: 4200,
    country: 'USA',
    stock: 3,
    description: 'A dermatologist-developed, lightweight moisturizer that provides all-day hydration while helping to restore the skin\'s natural barrier.',
    overview: 'CeraVe Moisturizing Lotion is a dermatologist-developed, lightweight moisturizer that provides all-day hydration while helping to restore the skin\'s natural barrier. Formulated with three essential ceramides and hyaluronic acid, this fast-absorbing, oil-free lotion keeps skin soft, smooth, and healthy-looking.',
    benefits: [
      'Provides long-lasting hydration',
      'Restores and strengthens the skin\'s natural barrier',
      'Non-comedogenic and fragrance-free',
      'Absorbs quickly with a lightweight, non-greasy finish',
      'Can be used on face and body',
    ],
    ingredients: [
      { name: 'Ceramides (1, 3, 6-II)', description: 'Help restore and maintain the skin\'s protective barrier' },
      { name: 'Hyaluronic Acid', description: 'Hydrates and plumps the skin by attracting moisture' },
      { name: 'Glycerin', description: 'Draws water into the skin for deep hydration' },
    ],
    howToUse: [
      'Apply to clean skin as often as needed, both morning and night.',
      'Suitable for use on the face and body.',
      'For best results, apply immediately after bathing or washing.',
    ],
    specificationTags: ['Normal Skin', 'Dry Skin', 'Sensitive Skin', 'All Ages', 'Fragrance-Free'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-FACIAL-LOTION-PM-52'),
    sku: 'CV-FACIAL-LOTION-PM-52',
    name: 'CeraVe Facial Moisturizing Lotion PM',
    brand: 'CeraVe',
    category: 'Moisturizers',
    type: '52ml',
    price: 13.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products/facial-moisturizing-lotion-pm/facial-moisturizing-lotion-pm_front.jpg?rev=c5e3e3e3&w=900',
    rating: 4.7,
    reviews: 3100,
    country: 'USA',
    stock: 2,
    description: 'A lightweight, oil-free night cream developed with dermatologists to help restore the skin\'s protective barrier while you sleep.',
    overview: 'CeraVe Facial Moisturizing Lotion PM is a lightweight, oil-free night cream developed with dermatologists to help restore the skin\'s protective barrier while you sleep. Enriched with ceramides, niacinamide, and hyaluronic acid.',
    benefits: [
      'Provides long-lasting hydration overnight',
      'Restores and strengthens the skin\'s natural barrier',
      'Soothes and calms the skin while reducing visible redness',
      'Non-comedogenic, fragrance-free, and oil-free',
      'Ideal for daily nighttime use',
    ],
    ingredients: [
      { name: 'Ceramides (1, 3, 6-II)', description: 'Help repair and protect the skin\'s barrier' },
      { name: 'Niacinamide', description: 'Calms the skin and improves tone and texture' },
      { name: 'Hyaluronic Acid', description: 'Attracts moisture to keep skin hydrated' },
      { name: 'Glycerin', description: 'Deeply hydrates and prevents moisture loss' },
    ],
    howToUse: [
      'Apply to clean face and neck in the evening as the final step in your nighttime skincare routine.',
      'Suitable for daily use. Avoid contact with eyes.',
    ],
    specificationTags: ['Normal Skin', 'Oily Skin', 'Combination Skin', 'Sensitive Skin', 'Night Cream'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-FACIAL-LOTION-AM-SPF50-52'),
    sku: 'CV-FACIAL-LOTION-AM-SPF50-52',
    name: 'CeraVe Facial Moisturizing Lotion AM SPF 50',
    brand: 'CeraVe',
    category: 'Sunscreen',
    type: '52ml',
    price: 15.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products/facial-moisturizing-lotion-am/facial-moisturizing-lotion-am-spf50_front.jpg?rev=d5e3e3e3&w=900',
    rating: 4.7,
    reviews: 2800,
    country: 'USA',
    stock: 2,
    description: 'A multitasking daytime moisturizer with broad-spectrum SPF 50 sun protection.',
    overview: 'CeraVe Facial Moisturizing Lotion AM SPF 50 is a multitasking daytime moisturizer developed with dermatologists to provide all-day hydration while offering high-level protection against UVA and UVB rays.',
    benefits: [
      'Hydrates and helps restore the skin\'s protective barrier',
      'Provides broad-spectrum SPF 50 sun protection',
      'Lightweight, non-greasy formula',
      'Fragrance-free and non-comedogenic',
      'Can be worn alone or under makeup',
    ],
    ingredients: [
      { name: 'Ceramides (1, 3, 6-II)', description: 'Help restore and maintain the skin\'s natural barrier' },
      { name: 'Niacinamide', description: 'Soothes the skin and improves overall texture' },
      { name: 'Hyaluronic Acid', description: 'Provides long-lasting hydration' },
      { name: 'Broad-Spectrum UV Filters (SPF 50)', description: 'Avobenzone, Homosalate, Octisalate, Octocrylene' },
    ],
    howToUse: [
      'Apply evenly to face and neck in the morning as the last step in your skincare routine.',
      'Reapply every two hours when exposed to sunlight.',
    ],
    specificationTags: ['Normal Skin', 'Dry Skin', 'Sensitive Skin', 'Sun Protection', 'SPF 50'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-EYE-REPAIR-CREAM-14'),
    sku: 'CV-EYE-REPAIR-CREAM-14',
    name: 'CeraVe Eye Repair Cream',
    brand: 'CeraVe',
    category: 'Eye Care',
    type: '14ml',
    price: 12.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products/eye-repair-cream/eye-repair-cream_front.jpg?rev=e5e3e3e3&w=900',
    rating: 4.6,
    reviews: 1800,
    country: 'USA',
    stock: 2,
    description: 'A dermatologist-developed formula designed to visibly reduce dark circles and puffiness around the delicate eye area.',
    overview: 'CeraVe Eye Repair Cream is a dermatologist-developed formula designed to visibly reduce dark circles and puffiness around the delicate eye area. Enriched with essential ceramides, hyaluronic acid, and niacinamide.',
    benefits: [
      'Reduces the appearance of dark circles and under-eye puffiness',
      'Restores and maintains the skin\'s protective barrier',
      'Hydrates and smooths the delicate eye area',
      'Fragrance-free, non-comedogenic, and suitable for sensitive eyes',
      'Can be used both morning and night',
    ],
    ingredients: [
      { name: 'Ceramides (1, 3, 6-II)', description: 'Help restore and maintain the skin\'s natural barrier' },
      { name: 'Hyaluronic Acid', description: 'Provides long-lasting hydration' },
      { name: 'Niacinamide', description: 'Soothes the skin and improves uneven tone' },
      { name: 'Marine & Botanical Extracts', description: 'Help brighten and refresh the eye area' },
    ],
    howToUse: [
      'Apply a small amount around the eye area using your ring finger.',
      'Gently pat into the skin until fully absorbed.',
      'Use in the morning and evening as part of your skincare routine.',
    ],
    specificationTags: ['All Skin Types', 'Sensitive Skin', 'Dark Circles', 'Eye Care', 'Puffiness'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-ADVANCED-REPAIR-OINTMENT-85'),
    sku: 'CV-ADVANCED-REPAIR-OINTMENT-85',
    name: 'CeraVe Advanced Repair Ointment',
    brand: 'CeraVe',
    category: 'Body Care',
    type: '85g / 144g',
    price: 11.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products/advanced-repair-ointment/advanced-repair-ointment_front.jpg?rev=f5e3e3e3&w=900',
    rating: 4.7,
    reviews: 1400,
    country: 'USA',
    stock: 2,
    description: 'A healing, multi-purpose ointment developed with dermatologists to protect and relieve dry, cracked, or chafed skin.',
    overview: 'CeraVe Advanced Repair Ointment is a healing, multi-purpose ointment developed with dermatologists to protect and relieve dry, cracked, or chafed skin. Formulated with ceramides, hyaluronic acid, and petrolatum.',
    benefits: [
      'Protects and soothes very dry, cracked, or irritated skin',
      'Forms a barrier to lock in moisture and aid healing',
      'Restores the skin\'s natural protective barrier',
      'Fragrance-free, lanolin-free, and non-comedogenic',
      'Gentle enough for sensitive skin and safe for all ages',
    ],
    ingredients: [
      { name: 'Ceramides (1, 3, 6-II)', description: 'Help restore and strengthen the skin\'s barrier' },
      { name: 'Hyaluronic Acid', description: 'Attracts hydration to support healing' },
      { name: 'Petrolatum', description: 'Forms a protective seal to prevent moisture loss' },
      { name: 'Dimethicone', description: 'Provides a silky, soothing texture' },
    ],
    howToUse: [
      'Apply as needed to dry, cracked, or irritated skin.',
      'Use on areas like hands, feet, elbows, lips, or any place needing extra hydration.',
      'Safe for daily use.',
    ],
    specificationTags: ['Dry Skin', 'Sensitive Skin', 'Eczema', 'All Ages', 'Healing'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-CREAM-TO-FOAM-CLEANSER-236'),
    sku: 'CV-CREAM-TO-FOAM-CLEANSER-236',
    name: 'CeraVe Hydrating Cream-to-Foam Cleanser',
    brand: 'CeraVe',
    category: 'Cleansers',
    type: '236ml',
    price: 12.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products/hydrating-cream-to-foam-cleanser/hydrating-cream-to-foam-cleanser_front.jpg?rev=a6e3e3e3&w=900',
    rating: 4.7,
    reviews: 2200,
    country: 'USA',
    stock: 2,
    description: 'A unique, one-step facial cleanser that begins as a rich cream and transforms into a gentle foam.',
    overview: 'CeraVe Hydrating Cream-to-Foam Cleanser is a unique, one-step facial cleanser that begins as a rich cream and transforms into a gentle foam. Effectively removes dirt, excess oil, and makeup without stripping the skin of moisture.',
    benefits: [
      'Effectively cleanses while maintaining skin hydration',
      'Removes makeup, dirt, and oil without disrupting the skin barrier',
      'Transforms from cream to foam for a gentle yet refreshing cleanse',
      'Fragrance-free, non-comedogenic, and pH-balanced',
      'Leaves skin feeling clean, soft, and comforted',
    ],
    ingredients: [
      { name: 'Amino Acids', description: 'Help support skin\'s natural hydration and cleansing process' },
      { name: 'Ceramides (1, 3, 6-II)', description: 'Restore and protect the skin\'s barrier' },
      { name: 'Hyaluronic Acid', description: 'Attracts and retains moisture for lasting hydration' },
      { name: 'Glycerin', description: 'Provides additional hydration and softening' },
    ],
    howToUse: [
      'Wet face with lukewarm water.',
      'Dispense cleanser into hands and gently massage into skin, allowing it to foam.',
      'Rinse thoroughly and pat dry. Use morning and night.',
    ],
    specificationTags: ['Normal Skin', 'Dry Skin', 'Sensitive Skin', 'Gentle Cleansing'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-FOAMING-CLEANSER-236'),
    sku: 'CV-FOAMING-CLEANSER-236',
    name: 'CeraVe Foaming Cleanser',
    brand: 'CeraVe',
    category: 'Cleansers',
    type: '236ml / 473ml',
    price: 11.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products/foaming-facial-cleanser/foaming-facial-cleanser_front.jpg?rev=b6e3e3e3&w=900',
    rating: 4.7,
    reviews: 4800,
    country: 'USA',
    stock: 3,
    description: 'A dermatologist-developed, gentle foaming gel cleanser designed to deeply cleanse the skin without disrupting its natural barrier.',
    overview: 'CeraVe Foaming Cleanser is a dermatologist-developed, gentle foaming gel cleanser designed to deeply cleanse the skin without disrupting its natural barrier. Enriched with ceramides, niacinamide, and hyaluronic acid.',
    benefits: [
      'Deeply cleanses and removes oil, dirt, and makeup',
      'Maintains the skin\'s protective barrier',
      'Refreshing foaming gel texture',
      'Non-comedogenic, fragrance-free, and non-irritating',
      'Leaves skin feeling fresh, not tight or dry',
    ],
    ingredients: [
      { name: 'Ceramides (1, 3, 6-II)', description: 'Support skin barrier restoration and protection' },
      { name: 'Niacinamide', description: 'Helps calm and soothe the skin' },
      { name: 'Hyaluronic Acid', description: 'Hydrates and retains moisture in the skin' },
      { name: 'Glycerin', description: 'A gentle humectant that enhances skin softness' },
    ],
    howToUse: [
      'Wet face with lukewarm water.',
      'Massage cleanser into skin in gentle, circular motions.',
      'Rinse thoroughly and pat dry. Use morning and evening.',
    ],
    specificationTags: ['Normal Skin', 'Oily Skin', 'Combination Skin', 'Acne-Prone', 'Gentle Cleansing'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-HYDRATING-CLEANSER-236'),
    sku: 'CV-HYDRATING-CLEANSER-236',
    name: 'CeraVe Hydrating Cleanser',
    brand: 'CeraVe',
    category: 'Cleansers',
    type: '236ml / 473ml',
    price: 11.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products/hydrating-facial-cleanser/hydrating-facial-cleanser_front.jpg?rev=c6e3e3e3&w=900',
    rating: 4.7,
    reviews: 3900,
    country: 'USA',
    stock: 3,
    description: 'A non-foaming, creamy cleanser developed with dermatologists to cleanse the skin without disrupting the natural moisture barrier.',
    overview: 'CeraVe Hydrating Cleanser is a non-foaming, creamy cleanser developed with dermatologists to cleanse the skin without disrupting the natural moisture barrier. Formulated with ceramides and hyaluronic acid.',
    benefits: [
      'Gently cleanses without stripping moisture',
      'Helps restore and maintain the skin\'s protective barrier',
      'Non-foaming, creamy texture',
      'Fragrance-free, non-comedogenic, and pH balanced',
      'Leaves skin soft, soothed, and hydrated',
    ],
    ingredients: [
      { name: 'Ceramides (1, 3, 6-II)', description: 'Strengthen the skin\'s natural barrier' },
      { name: 'Hyaluronic Acid', description: 'Attracts and retains moisture' },
      { name: 'Glycerin', description: 'Softens and hydrates the skin' },
      { name: 'Cetearyl Alcohol', description: 'A moisturizing agent that improves skin feel' },
    ],
    howToUse: [
      'Wet skin with lukewarm water.',
      'Massage cleanser into skin with gentle, circular motions.',
      'Rinse thoroughly or wipe off with a soft cloth. Use morning and evening.',
    ],
    specificationTags: ['Normal Skin', 'Dry Skin', 'Sensitive Skin', 'All Ages', 'Gentle Cleansing'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-FOAMING-OIL-CLEANSER-236'),
    sku: 'CV-FOAMING-OIL-CLEANSER-236',
    name: 'CeraVe Hydrating Foaming Oil Cleanser',
    brand: 'CeraVe',
    category: 'Cleansers',
    type: '236ml / 355ml / 473ml',
    price: 13.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products/hydrating-foaming-oil-cleanser/hydrating-foaming-oil-cleanser_front.jpg?rev=d6e3e3e3&w=900',
    rating: 4.7,
    reviews: 2600,
    country: 'USA',
    stock: 3,
    description: 'A gentle yet effective daily cleanser that starts as a lightweight oil and transforms into a soft foam.',
    overview: 'CeraVe Hydrating Foaming Oil Cleanser is a gentle yet effective daily cleanser that starts as a lightweight oil and transforms into a soft foam to cleanse the skin without disrupting its natural barrier. Contains three essential ceramides, squalane, triglycerides, and hyaluronic acid.',
    benefits: [
      'Effectively cleanses without stripping the skin of moisture',
      'Transforms from oil to foam for a luxurious, gentle cleansing experience',
      'Restores and maintains the skin\'s protective barrier',
      'Fragrance-free, non-comedogenic, and pH-balanced',
      'Leaves skin soft, soothed, and hydrated',
    ],
    ingredients: [
      { name: 'Ceramides (1, 3, 6-II)', description: 'Restore and support the skin\'s natural barrier' },
      { name: 'Squalane', description: 'Mimics the skin\'s natural oils to provide lightweight moisture' },
      { name: 'Hyaluronic Acid', description: 'Draws and retains moisture in the skin' },
      { name: 'Triglycerides', description: 'Help replenish essential skin lipids' },
    ],
    howToUse: [
      'Apply to wet skin and gently massage until it transforms from oil to foam.',
      'Rinse thoroughly. Use daily in the morning and evening.',
      'Safe for use on both face and body.',
    ],
    specificationTags: ['Normal Skin', 'Dry Skin', 'Sensitive Skin', 'Eczema', 'Gentle Cleansing'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-BLEMISH-CONTROL-CLEANSER-236'),
    sku: 'CV-BLEMISH-CONTROL-CLEANSER-236',
    name: 'CeraVe Blemish Control Cleanser',
    brand: 'CeraVe',
    category: 'Cleansers',
    type: '236ml',
    price: 12.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/skincare/acne/acne/acne-control-gel/acne-control-gel_front.jpg?rev=4d14072c94364d2dbde6321bc913cbff&w=900',
    rating: 4.6,
    reviews: 1700,
    country: 'USA',
    stock: 2,
    description: 'A clarifying cleanser with 2% Salicylic Acid for acne-prone skin.',
    overview: 'CeraVe Blemish Control Cleanser is a gentle yet effective daily face wash formulated with 2% salicylic acid to help clear acne breakouts, unclog pores, and reduce blackheads. Combines niacinamide, ceramides, and hyaluronic acid.',
    benefits: [
      'Helps clear acne, blackheads, and blemishes',
      'Gently exfoliates and unclogs pores',
      'Maintains the skin\'s protective barrier',
      'Non-drying, non-comedogenic, and fragrance-free',
      'Prepares skin for better absorption of treatments and moisturizers',
    ],
    ingredients: [
      { name: 'Salicylic Acid', percentage: '2%', description: 'Penetrates pores to reduce acne and prevent new breakouts' },
      { name: 'Niacinamide', description: 'Soothes and calms the skin while supporting clarity' },
      { name: 'Ceramides (1, 3, 6-II)', description: 'Restore and maintain the skin\'s natural barrier' },
      { name: 'Hyaluronic Acid', description: 'Helps retain moisture for balanced hydration' },
    ],
    howToUse: [
      'Wet face with lukewarm water.',
      'Massage cleanser into skin gently, avoiding the eye area.',
      'Rinse thoroughly. Use once or twice daily.',
    ],
    specificationTags: ['Oily Skin', 'Acne-Prone', 'Combination Skin', 'Blemish Control', 'Exfoliating'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-SA-SMOOTHING-CLEANSER-236'),
    sku: 'CV-SA-SMOOTHING-CLEANSER-236',
    name: 'CeraVe SA Smoothing Cleanser',
    brand: 'CeraVe',
    category: 'Cleansers',
    type: '236ml / 473ml',
    price: 12.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/skincare/2025/renewing-sa-cleanser/renewing-sa-cleanser_front.jpg?rev=09693b68b6834f7fb18f8fefca67c151&w=900',
    rating: 4.6,
    reviews: 1900,
    country: 'USA',
    stock: 2,
    description: 'A non-irritating exfoliating face and body wash formulated with salicylic acid to gently remove dead skin cells and improve skin texture.',
    overview: 'CeraVe SA Smoothing Cleanser is a non-irritating exfoliating face and body wash formulated with salicylic acid to gently remove dead skin cells and improve skin texture without compromising the skin\'s barrier. Combines ceramides, niacinamide, and hyaluronic acid.',
    benefits: [
      'Exfoliates and smooths rough, uneven skin texture',
      'Gently removes dirt, oil, and dead skin without harsh microbeads',
      'Helps maintain and restore the skin\'s protective barrier',
      'Fragrance-free, non-comedogenic, and non-irritating',
      'Can be used on face and body',
    ],
    ingredients: [
      { name: 'Salicylic Acid', description: 'A beta hydroxy acid (BHA) that gently exfoliates and unclogs pores' },
      { name: 'Ceramides (1, 3, 6-II)', description: 'Help maintain and restore the skin\'s protective barrier' },
      { name: 'Niacinamide', description: 'Soothes and calms the skin' },
      { name: 'Hyaluronic Acid', description: 'Hydrates and helps retain skin moisture' },
    ],
    howToUse: [
      'Apply to wet skin and massage gently in circular motions.',
      'Rinse thoroughly. Avoid the eye area.',
      'Use once or twice daily. Follow with a suitable moisturizer.',
    ],
    specificationTags: ['Normal Skin', 'Dry Skin', 'Combination Skin', 'Keratosis Pilaris', 'Exfoliating'],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: makeId('CV-SA-SMOOTHING-CREAM-177'),
    sku: 'CV-SA-SMOOTHING-CREAM-177',
    name: 'CeraVe SA Smoothing Cream',
    brand: 'CeraVe',
    category: 'Moisturizers',
    type: '177ml',
    price: 14.90,
    image: 'https://www.cerave.com/-/media/project/loreal/brand-sites/cerave/americas/us/products/sa-smoothing-cream/sa-smoothing-cream_front.jpg?rev=e6e3e3e3&w=900',
    rating: 4.6,
    reviews: 1500,
    country: 'USA',
    stock: 2,
    description: 'A rich, non-greasy moisturizer formulated to gently exfoliate and deeply hydrate rough, bumpy, and dry skin.',
    overview: 'CeraVe SA Smoothing Cream is a rich, non-greasy moisturizer formulated to gently exfoliate and deeply hydrate rough, bumpy, and dry skin. Combines salicylic acid, ceramides, niacinamide, and hyaluronic acid to smooth skin texture and help restore the skin\'s natural barrier.',
    benefits: [
      'Exfoliates rough and bumpy skin to improve texture',
      'Provides long-lasting hydration and barrier support',
      'Non-comedogenic, fragrance-free, and non-irritating',
      'Softens dry, thick skin on arms, legs, elbows, and other problem areas',
      'Suitable for face and body',
    ],
    ingredients: [
      { name: 'Salicylic Acid', description: 'Gently exfoliates and helps clear dead skin cells' },
      { name: 'Ceramides (1, 3, 6-II)', description: 'Help restore and maintain the skin\'s natural protective barrier' },
      { name: 'Niacinamide', description: 'Helps soothe and calm the skin' },
      { name: 'Hyaluronic Acid', description: 'Attracts and retains moisture' },
      { name: 'Lactic Acid', description: 'Supports exfoliation and skin renewal' },
    ],
    howToUse: [
      'Apply to affected areas once or twice daily.',
      'Do not apply to broken or irritated skin. Avoid contact with eyes.',
      'For best results, use in conjunction with CeraVe SA Smoothing Cleanser.',
    ],
    specificationTags: ['Dry Skin', 'Keratosis Pilaris', 'Rough Skin', 'Exfoliating', 'Body Care'],
    createdAt: now,
    updatedAt: now,
  },
];
